const state={resolve:null,mode:null,busy:false};

function ensureStyles(){if(document.querySelector('link[href="northstar-dialogs.css"]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='northstar-dialogs.css';document.head.appendChild(link)}
function ensureUi(){ensureStyles();if(document.querySelector('#northstarDialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="northstarDialog" class="northstar-dialog"><form id="northstarDialogForm" class="northstar-dialog-card" method="dialog"><div class="northstar-dialog-head"><div><p class="eyebrow" id="northstarDialogEyebrow">Northstar Medical Center</p><h3 id="northstarDialogTitle">Northstar</h3></div><button class="northstar-dialog-close" type="button" data-ns-dialog-cancel aria-label="Close">×</button></div><div class="northstar-dialog-body"><p id="northstarDialogMessage" class="northstar-dialog-message"></p><label id="northstarDialogField" class="northstar-dialog-field" hidden><span id="northstarDialogLabel">Value</span><input id="northstarDialogInput" autocomplete="off"><textarea id="northstarDialogTextarea" hidden></textarea></label><p id="northstarDialogError" class="northstar-dialog-error"></p></div><div class="northstar-dialog-footer"><button id="northstarDialogCancel" class="northstar-dialog-cancel" type="button" data-ns-dialog-cancel>Cancel</button><button id="northstarDialogConfirm" class="northstar-dialog-confirm" type="submit">Confirm</button></div></form></dialog>`);
const dialog=document.querySelector('#northstarDialog');document.querySelectorAll('[data-ns-dialog-cancel]').forEach(b=>b.addEventListener('click',()=>finish(state.mode==='alert'?true:null)));document.querySelector('#northstarDialogForm').addEventListener('submit',e=>{e.preventDefault();submit()});dialog.addEventListener('cancel',e=>{e.preventDefault();finish(state.mode==='alert'?true:null)});dialog.addEventListener('click',e=>{if(e.target===dialog)finish(state.mode==='alert'?true:null)})}
function setText(sel,value){const n=document.querySelector(sel);if(n)n.textContent=value??''}
function activeInput(){return document.querySelector('#northstarDialogTextarea')?.hidden?document.querySelector('#northstarDialogInput'):document.querySelector('#northstarDialogTextarea')}
function open(options={}){ensureUi();if(state.busy)return Promise.reject(new Error('A Northstar dialog is already open.'));state.busy=true;state.mode=options.mode||'confirm';const dialog=document.querySelector('#northstarDialog');dialog.className=`northstar-dialog${options.tone?` ${options.tone}`:''}`;setText('#northstarDialogEyebrow',options.eyebrow||'Northstar Medical Center');setText('#northstarDialogTitle',options.title||'Northstar');setText('#northstarDialogMessage',options.message||'');setText('#northstarDialogConfirm',options.confirmText||(state.mode==='alert'?'OK':'Confirm'));setText('#northstarDialogCancel',options.cancelText||'Cancel');setText('#northstarDialogError','');const cancel=document.querySelector('#northstarDialogCancel');cancel.hidden=state.mode==='alert';const field=document.querySelector('#northstarDialogField');const input=document.querySelector('#northstarDialogInput');const textarea=document.querySelector('#northstarDialogTextarea');field.hidden=state.mode!=='prompt';input.hidden=state.mode!=='prompt'||options.multiline===true;textarea.hidden=state.mode!=='prompt'||options.multiline!==true;if(state.mode==='prompt'){setText('#northstarDialogLabel',options.label||'Response');const control=options.multiline?textarea:input;control.value=options.value??'';control.placeholder=options.placeholder||'';control.dataset.required=options.required?'1':'0';control.dataset.minLength=String(options.minLength||0);control.type=options.inputType||'text'}return new Promise(resolve=>{state.resolve=resolve;dialog.showModal();setTimeout(()=>{if(state.mode==='prompt')activeInput()?.focus();else document.querySelector('#northstarDialogConfirm')?.focus()},20)})}
function submit(){if(state.mode==='prompt'){const control=activeInput();const value=String(control?.value??'');const required=control?.dataset.required==='1';const minLength=Number(control?.dataset.minLength||0);if(required&&!value.trim()){setText('#northstarDialogError','This field is required.');control?.focus();return}if(value.trim().length<minLength){setText('#northstarDialogError',`Enter at least ${minLength} characters.`);control?.focus();return}finish(value);return}finish(true)}
function finish(value){const dialog=document.querySelector('#northstarDialog');if(dialog?.open)dialog.close();const resolve=state.resolve;state.resolve=null;state.mode=null;state.busy=false;resolve?.(value)}

window.NorthstarDialog={
  alert:(options={})=>open({...options,mode:'alert'}),
  confirm:(options={})=>open({...options,mode:'confirm'}).then(Boolean),
  prompt:(options={})=>open({...options,mode:'prompt'})
};
